export const COUNTRIES = [
  { label: "South Georgia", value: "GS" },
  { label: "Grenada", value: "GD" },
  { label: "Switzerland", value: "CH" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Hungary", value: "HU" },
  { label: "Taiwan", value: "TW" },
  { label: "Wallis and Futuna", value: "WF" },
  { label: "Barbados", value: "BB" },
  { label: "Pitcairn Islands", value: "PN" },
  { label: "Ivory Coast", value: "CI" },
  { label: "Tunisia", value: "TN" },
  { label: "Italy", value: "IT" },
  { label: "Benin", value: "BJ" },
  { label: "Indonesia", value: "ID" },
  { label: "Cape Verde", value: "CV" },
  { label: "Saint Kitts and Nevis", value: "KN" },
  { label: "Laos", value: "LA" },
  { label: "Caribbean Netherlands", value: "BQ" },
  { label: "Uganda", value: "UG" },
  { label: "Andorra", value: "AD" },
  { label: "Burundi", value: "BI" },
  { label: "South Africa", value: "ZA" },
  { label: "France", value: "FR" },
  { label: "Libya", value: "LY" },
  { label: "Mexico", value: "MX" },
  { label: "Gabon", value: "GA" },
  { label: "Northern Mariana Islands", value: "MP" },
  { label: "North Macedonia", value: "MK" },
  { label: "China", value: "CN" },
  { label: "Yemen", value: "YE" },
  { label: "Saint BarthÃ©lemy", value: "BL" },
  { label: "Guernsey", value: "GG" },
  { label: "Solomon Islands", value: "SB" },
  { label: "Svalbard and Jan Mayen", value: "SJ" },
  { label: "Faroe Islands", value: "FO" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "Egypt", value: "EG" },
  { label: "Senegal", value: "SN" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Palestine", value: "PS" },
  { label: "Bangladesh", value: "BD" },
  { label: "Peru", value: "PE" },
  { label: "Singapore", value: "SG" },
  { label: "Turkey", value: "TR" },
  { label: "Afghanistan", value: "AF" },
  { label: "Aruba", value: "AW" },
  { label: "Cook Islands", value: "CK" },
  { label: "United Kingdom", value: "GB" },
  { label: "Zambia", value: "ZM" },
  { label: "Finland", value: "FI" },
  { label: "Niger", value: "NE" },
  { label: "Christmas Island", value: "CX" },
  { label: "Tokelau", value: "TK" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "RÃ©union", value: "RE" },
  { label: "Djibouti", value: "DJ" },
  { label: "North Korea", value: "KP" },
  { label: "Mauritius", value: "MU" },
  { label: "Montserrat", value: "MS" },
  { label: "United States Virgin Islands", value: "VI" },
  { label: "Colombia", value: "CO" },
  { label: "Greece", value: "GR" },
  { label: "Croatia", value: "HR" },
  { label: "Morocco", value: "MA" },
  { label: "Algeria", value: "DZ" },
  { label: "Antarctica", value: "AQ" },
  { label: "Netherlands", value: "NL" },
  { label: "Sudan", value: "SD" },
  { label: "Fiji", value: "FJ" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Nepal", value: "NP" },
  { label: "Puerto Rico", value: "PR" },
  { label: "Georgia", value: "GE" },
  { label: "Pakistan", value: "PK" },
  { label: "Monaco", value: "MC" },
  { label: "Botswana", value: "BW" },
  { label: "Lebanon", value: "LB" },
  { label: "Papua New Guinea", value: "PG" },
  { label: "Mayotte", value: "YT" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Norfolk Island", value: "NF" },
  { label: "Bouvet Island", value: "BV" },
  { label: "Qatar", value: "QA" },
  { label: "Madagascar", value: "MG" },
  { label: "India", value: "IN" },
  { label: "Syria", value: "SY" },
  { label: "Montenegro", value: "ME" },
  { label: "Eswatini", value: "SZ" },
  { label: "Paraguay", value: "PY" },
  { label: "El Salvador", value: "SV" },
  { label: "Ukraine", value: "UA" },
  { label: "Isle of Man", value: "IM" },
  { label: "Namibia", value: "NA" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "Bulgaria", value: "BG" },
  { label: "Greenland", value: "GL" },
  { label: "Germany", value: "DE" },
  { label: "Cambodia", value: "KH" },
  { label: "Iraq", value: "IQ" },
  { label: "French Southern and Antarctic Lands", value: "TF" },
  { label: "Sweden", value: "SE" },
  { label: "Cuba", value: "CU" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Russia", value: "RU" },
  { label: "Malaysia", value: "MY" },
  { label: "SÃ£o TomÃ© and PrÃ­ncipe", value: "ST" },
  { label: "Cyprus", value: "CY" },
  { label: "Canada", value: "CA" },
  { label: "Malawi", value: "MW" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Bosnia and Herzegovina", value: "BA" },
  { label: "Ethiopia", value: "ET" },
  { label: "Spain", value: "ES" },
  { label: "Slovenia", value: "SI" },
  { label: "Oman", value: "OM" },
  { label: "Saint Pierre and Miquelon", value: "PM" },
  { label: "Macau", value: "MO" },
  { label: "San Marino", value: "SM" },
  { label: "Lesotho", value: "LS" },
  { label: "Marshall Islands", value: "MH" },
  { label: "Sint Maarten", value: "SX" },
  { label: "Iceland", value: "IS" },
  { label: "Luxembourg", value: "LU" },
  { label: "Argentina", value: "AR" },
  { label: "Turks and Caicos Islands", value: "TC" },
  { label: "Nauru", value: "NR" },
  { label: "Cocos (Keeling) Islands", value: "CC" },
  { label: "Western Sahara", value: "EH" },
  { label: "Dominica", value: "DM" },
  { label: "Costa Rica", value: "CR" },
  { label: "Australia", value: "AU" },
  { label: "Thailand", value: "TH" },
  { label: "Haiti", value: "HT" },
  { label: "Tuvalu", value: "TV" },
  { label: "Honduras", value: "HN" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Saint Lucia", value: "LC" },
  { label: "French Polynesia", value: "PF" },
  { label: "Belarus", value: "BY" },
  { label: "Latvia", value: "LV" },
  { label: "Palau", value: "PW" },
  { label: "Guadeloupe", value: "GP" },
  { label: "Philippines", value: "PH" },
  { label: "Gibraltar", value: "GI" },
  { label: "Denmark", value: "DK" },
  { label: "Cameroon", value: "CM" },
  { label: "Guinea", value: "GN" },
  { label: "Bahrain", value: "BH" },
  { label: "Suriname", value: "SR" },
  { label: "DR Congo", value: "CD" },
  { label: "Somalia", value: "SO" },
  { label: "Czechia", value: "CZ" },
  { label: "New Caledonia", value: "NC" },
  { label: "Vanuatu", value: "VU" },
  { label: "Saint Helena, Ascension and Tristan da Cunha", value: "SH" },
  { label: "Togo", value: "TG" },
  { label: "British Virgin Islands", value: "VG" },
  { label: "Kenya", value: "KE" },
  { label: "Niue", value: "NU" },
  { label: "Heard Island and McDonald Islands", value: "HM" },
  { label: "Rwanda", value: "RW" },
  { label: "Estonia", value: "EE" },
  { label: "Romania", value: "RO" },
  { label: "Trinidad and Tobago", value: "TT" },
  { label: "Guyana", value: "GY" },
  { label: "Timor-Leste", value: "TL" },
  { label: "Vietnam", value: "VN" },
  { label: "Uruguay", value: "UY" },
  { label: "Vatican City", value: "VA" },
  { label: "Hong Kong", value: "HK" },
  { label: "Austria", value: "AT" },
  { label: "Antigua and Barbuda", value: "AG" },
  { label: "Turkmenistan", value: "TM" },
  { label: "Mozambique", value: "MZ" },
  { label: "Panama", value: "PA" },
  { label: "Micronesia", value: "FM" },
  { label: "Ireland", value: "IE" },
  { label: "CuraÃ§ao", value: "CW" },
  { label: "French Guiana", value: "GF" },
  { label: "Norway", value: "NO" },
  { label: "Ã…land Islands", value: "AX" },
  { label: "Central African Republic", value: "CF" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Eritrea", value: "ER" },
  { label: "Tanzania", value: "TZ" },
  { label: "South Korea", value: "KR" },
  { label: "Jordan", value: "JO" },
  { label: "Mauritania", value: "MR" },
  { label: "Lithuania", value: "LT" },
  { label: "United States Minor Outlying Islands", value: "UM" },
  { label: "Slovakia", value: "SK" },
  { label: "Angola", value: "AO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Moldova", value: "MD" },
  { label: "Mali", value: "ML" },
  { label: "Falkland Islands", value: "FK" },
  { label: "Armenia", value: "AM" },
  { label: "Samoa", value: "WS" },
  { label: "Jersey", value: "JE" },
  { label: "Japan", value: "JP" },
  { label: "Bolivia", value: "BO" },
  { label: "Chile", value: "CL" },
  { label: "United States", value: "US" },
  { label: "Saint Vincent and the Grenadines", value: "VC" },
  { label: "Bermuda", value: "BM" },
  { label: "Seychelles", value: "SC" },
  { label: "British Indian Ocean Territory", value: "IO" },
  { label: "Guatemala", value: "GT" },
  { label: "Ecuador", value: "EC" },
  { label: "Martinique", value: "MQ" },
  { label: "Tajikistan", value: "TJ" },
  { label: "Malta", value: "MT" },
  { label: "Gambia", value: "GM" },
  { label: "Nigeria", value: "NG" },
  { label: "Bahamas", value: "BS" },
  { label: "Kosovo", value: "XK" },
  { label: "Kuwait", value: "KW" },
  { label: "Maldives", value: "MV" },
  { label: "South Sudan", value: "SS" },
  { label: "Iran", value: "IR" },
  { label: "Albania", value: "AL" },
  { label: "Brazil", value: "BR" },
  { label: "Serbia", value: "RS" },
  { label: "Belize", value: "BZ" },
  { label: "Myanmar", value: "MM" },
  { label: "Bhutan", value: "BT" },
  { label: "Venezuela", value: "VE" },
  { label: "Liberia", value: "LR" },
  { label: "Jamaica", value: "JM" },
  { label: "Poland", value: "PL" },
  { label: "Cayman Islands", value: "KY" },
  { label: "Brunei", value: "BN" },
  { label: "Comoros", value: "KM" },
  { label: "Guam", value: "GU" },
  { label: "Tonga", value: "TO" },
  { label: "Kiribati", value: "KI" },
  { label: "Ghana", value: "GH" },
  { label: "Chad", value: "TD" },
  { label: "Zimbabwe", value: "ZW" },
  { label: "Saint Martin", value: "MF" },
  { label: "Mongolia", value: "MN" },
  { label: "Portugal", value: "PT" },
  { label: "American Samoa", value: "AS" },
  { label: "Republic of the Congo", value: "CG" },
  { label: "Belgium", value: "BE" },
  { label: "Israel", value: "IL" },
  { label: "New Zealand", value: "NZ" },
  { label: "Nicaragua", value: "NI" },
  { label: "Anguilla", value: "AI" },
];

export type Country = (typeof COUNTRIES)[number];
export type CountryValue = Country["value"];
export type CountryLabel = Country["label"];
